#!/usr/bin/node

let n = Number(process.argv[2])
function factorial(num) {
    if (isNaN(num) || num < 0) return 'invalid agrument!'
    if (num === 0) return 1
    return factorial(num - 1) * num
}
let ans = String(factorial(n))
process.stdout.write(ans + "\n")
