#!/usr/bin/bash

cd ~/bin
num=$(( 1 + $RANDOM % 10))
echo $num >> fraud.txt
for x in $(seq 1 $num)
do 
echo $(date) >> fraud.txt
git add fraud.txt
git commit -m "Jesus loves you!!"
git push origin main
done
glog