#!/usr/bin/bash

#colors
c1=$( tput setaf 196 )
c2=$( tput setaf 21 )
c3=$( tput setaf 28 )
c4=$( tput setaf 118 )
c5=$( tput setaf 226 )
nc=$( tput sgr0 )

last_installed=`grep "Running 'pacman -S " /var/log/pacman.log |tail -1 | awk '{print $6}' | tr -d "'"`
d1=`grep "Running 'pacman -S " /var/log/pacman.log |tail -1 | awk '{print $1}' | tr -d "[]"`
d2=`date -d"$d1" +'%A %b %d'`
d3=`date -d"$d1" +'%I:%M %p'`

last_removed=`grep "Running 'pacman -R" /var/log/pacman.log |tail -1 | awk '{print $6}'| tr -d "'"`
d4=`grep "Running 'pacman -R" /var/log/pacman.log |tail -1 | awk '{print $1}' | tr -d "[]"`
d5=`date -d"$d4" +'%A %b %d'`
d6=`date -d"$d4" +'%I:%M %p'`

echo "Explicitely Installed Packages:      $c1$(pacman -Qe |wc -l)$nc"
echo "Packages Installed as Dependencies:  $c2$(pacman -Qd |wc -l)$nc"
echo "Total:                               $c3$(pacman -Q |wc -l)$nc"
echo "Packages installed from the AUR:     $c1$(\ls ~/AUR | wc -l)$nc"
echo "Last package explicitely installed:  $c4$last_installed$nc => Installed on $d2 at $d3"
echo "Last package explicitely removed:    $c5$last_removed$nc => Removed on $d5 at $d6"
