#!/usr/bin/bash

#colors
c1=$( tput setaf 196 )
c2=$( tput setaf 21 )
c3=$( tput setaf 28 )
c4=$( tput setaf 118 )
c5=$( tput setaf 226 )
nc=$( tput setaf 255 )

last_installed=`grep "Running 'pacman -S " /var/log/pacman.log |tail -1 | awk '{print $6}' | tr -d "'"`
last_removed=`grep "Running 'pacman -R" /var/log/pacman.log |tail -1 | awk '{print $6}'| tr -d "'"`

echo "Explicitely Installed Packages:      $c1$(pacman -Qe |wc -l)$nc"
echo "Packages installed as dependencies:  $c2$(pacman -Qd |wc -l)$nc"
echo "Total Packages installed:            $c3$(pacman -Q |wc -l)$nc"
echo "Last package explicitely installed:  $c4$last_installed$nc"
echo "Last package explicitely removed:    $c5$last_removed$nc"
