#!/usr/bin/bash
# Purpose: Make it easier to use macchanger
# Process: Show the current MAC address or change to a random address if correct argument is supplied  (show or change)
#          Curse like a nasty british dude if incorrect or no argument is supplied
#          It's required to first turn the wireless interface down before changing the MAC address
# Note:    NetworkManager will reset your spoofing attempt everytime it connects to a network. Therefore this is only
#          a temporary way to spoof. I have set NetworkManager's native MAC randomization so that everytime i connect
#          to a network, i get a random MAC address. Look up NetworkManager on Arch Wiki and search for MAC randomization.

wireless_interface=`iw dev | awk '$1=="Interface"{print $2}'`
curse='What the fucking hell are you?\nYou great-gangly-fuck-knuckle-twat.\nGreasy-head-cumbag.\nFuck You!!\n'

if [ $# -eq 0 ]; then
  printf "$curse"
elif [ $1 = "change" ]; then
  sudo ip link set $wireless_interface down
  sudo macchanger -br $wireless_interface
  sudo ip link set $wireless_interface up
elif [ $1 = "show" ]; then
  macchanger -s $wireless_interface
else printf "$curse"
fi
