#!/usr/bin/bash
# Purpose: Update packages installed with AUR.
# Process: Go into each directory, perform git pull, perform makepkg and climb back up
#          Save the date of update for reference

for aur in `\ls ~/Documents/AUR`
do cd ~/Documents/AUR/$aur
git pull 1> /tmp/smokinghot.xxx
i=`cat /tmp/smokinghot.xxx | awk '{ print $0 }'`
echo 'Hello!!' > /tmp/smokinghot.xxx
if [ "$i" = "Already up to date." ]
then  continue
else makepkg -sirc --noconfirm
  echo "$aur was successfully updated on $( date +'%b %d' ) at $( date +'%I:%M %p' )" >> ~/.aur_update_dates.log
fi
done
