#!/usr/bin/bash
# Purpose: Update packages installed with AUR.
# Process: Go into each directory, perform git pull, perform makepkg and climb back up
#          Save the date of update for reference

for aur in `\ls ~/AUR`
do cd ~/AUR/$aur
git pull 1> /tmp/smokinghot.xxx
i=`cat /tmp/smokinghot.xxx | awk '{ print $0 }'`
echo 'Hello!!' > /tmp/smokinghot.xxx
if [ "$i" = "Already up to date." ]
then  echo "$aur was up to date on $( date )" >> ~/.aur_update_dates && continue
else makepkg -sirc --noconfirm
  echo "$aur was updated on  $( date )" >> ~/.aur_update_dates.log
fi
done
