#!/usr/bin/bash
# Get color coded info on when your arch system was last updated with a single command: when
# This file should be executable and placed in you scripts directory

#colors
c1=$( tput setaf 196 )
c2=$( tput setaf 21 )
c3=$( tput setaf 28 )
nc=$( tput sgr0 )

#dates
d1=`grep Syu /var/log/pacman.log | tail -1 | awk '{ print $1 }' | tr -d '[]'`
d2=`date -d"$d1" +%s`

now=`date +%s`
diff=$(( now - d2 ))

days=$(( diff / 86400 ))
rem=$(( diff - days * 86400))
hours=$(( rem/3600 ))
rem=$(( rem - hours * 3600))
minutes=$(( rem / 60 ))
seconds=$(( rem - minutes  * 60 ))

echo "Your machine was last updated on $c1$(date -d"$d1" +'%A %b %d')$nc at$c1 $(date -d"$d1" +'%I:%M %p')$nc!"
echo "It has been $c2$days days, $hours hours, $minutes minutes and $seconds$nc seconds since then!!"
echo "Please remember to update your Arch Linux$c3 every week!!$nc"
